version: "3.3"
services:
  updatejson:
    image: ghcr.io/minecrafthopper/modmail
    restart: always
    depends_on:
      - database
    environment:
      MM_TOKEN: ${TOKEN}
      MM_MAIN_SERVER_ID: ${SERVER_ID}
      MM_INBOX_SERVER_ID: ${SERVER_ID}
      MM_LOG_CHANNEL_ID: ${LOG_CHANNEL_ID}
      MM_CATEGORY_AUTOMATION__NEW_THREAD: ${CATEGORY_ID}
      MM_DB_TYPE: sqlite
      MM_SQLITEOPTIONS__FILENAME: /db/database.db
    volumes:
      - "dbdata:/db"

volumes:
  dbdata:
