version: "3.3"
services:
  updatejson:
    image: ghcr.io/minecrafthopper/modmail
    restart: always
    depends_on:
      - database
    environment:
      MM_TOKEN: ${TOKEN}
      MM_MAIN_SERVER_ID: ${SERVER_ID}
      MM_INBOX_SERVER_ID: ${SERVER_ID}
      MM_LOG_CHANNEL_ID: ${LOG_CHANNEL_ID}
      MM_CATEGORY_AUTOMATION__NEW_THREAD: ${CATEGORY_ID}
      MM_DB_TYPE: sqlite
      MM_SQLITEOPTIONS__FILENAME: /db/database.db
      MM_URL: "${URL}"
    volumes:
      - "dbdata:/db"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.modmail.rule=Host(`${HOST}`)"
        - "traefik.http.routers.modmail.entrypoints=websecure"
        - "traefik.http.routers.modmail.tls.certresolver=myresolver"
        - "traefik.http.services.modmail.loadbalancer.server.port=8890"

volumes:
  dbdata:
